#!/usr/bin/python3
import sys
import zipfile
from datetime import datetime
from io import BytesIO

from source.target import *
from source import log

try:
    target_path = sys.argv[1]
    if target_path in ('-h', '--help'):
        log.info('Usage: %s [<target> [<output_zip_file>]]' % sys.argv[0])
        sys.exit(1)
except:
    target_path = '/'
try:
    output_zip = sys.argv[2]
except:
    output_zip = './scoop_%d.zip' % datetime.timestamp(datetime.now())
    log.info('Result will be stored in %s.' % output_zip)

# create target connection, dump interesting files
t = Target.create_target(target_path)
result = t.dump()
# craft zip
memzip = BytesIO()
with zipfile.ZipFile(memzip, mode='a', compression=zipfile.ZIP_DEFLATED) as zf:
    for k, v in result.items():
        if not v:
            continue
        zf.writestr(k, v)
# save the zip
with open(output_zip, 'wb') as f:
    f.write(memzip.getvalue())
log.ok('Files saved in %s.' % output_zip)
